### ISSUE TITLE
[Enhancement] Allow Image Viewer to be displayed in fullscreen mode and to browse all pics inside the same folder.

### ISSUE THREAD

**Issue by DrUm78** [od-contrib/commander#16]
Hello,

1. I think it would be nice to be able to use Image Viewer only in fullscreen mode without the left, right and top bars, no point to keep them I think.
2. Also, when an image is viewed, that would be useful to be able to use d-pad or L/R to display the previous/following image inside the same folder without having to press B to exit Image Viewer.
3. A preview of the current selected image would be awesome in the file browser too.

Thanks!

**Comment by glebm** [comment]
These are 3 separate things and should be separate issues.

(2) is addressed in https://github.com/od-contrib/commander/releases/tag/2022-11-01

(1) It is useful to know which image you're looking it, especially now that you can navigate through them.

**Comment by DrUm78** [comment]
Not sure this repo is still active but just in case you are interested, I implemented the fullscreen mode with the possibility to toggle the title bar and switch between the checkerboard and a new black background + a little "fix" that prevents the selection from going on ".." while in the image viewer. Here is the commit: https://github.com/DrUm78/commander/commit/d79509548073cd788b961f439737786120542dc0.

Next step for me is the implementation of some cool KAI features such as the left panel that can be expanded.

**Comment by glebm** [comment]
@DrUm78 Feel free to send a PR! I'm not developing it actively but happy to review contributions
