### ISSUE TITLE
Default font size is too large, global dpi is ignored

### ISSUE THREAD

**Issue by dfilskov** [od-contrib/commander#20]
Thank you for your work on this great tool for Batocera. It has made file handling and editing on Steam Deck so much easier :)

Please consider making the default scaling smaller and comply with the global.dpi setting in batocera.conf

It will make it possible to see longer filenames than this:

![IMG_20240512_192514~2](https://github.com/od-contrib/commander/assets/15096058/e38e8a0a-0b20-4385-913d-4cfd1d962f26)

I've tried changing batocera.conf

global.dpi=72

... but nothing changes.

**Comment by glebm** [comment]
The settings are named `disp_ppu_y` and `disp_ppu_x`.

**Comment by glebm** [comment]
You may also need to set `disp_autoscale_dpi` to `0`.

**Comment by dfilskov** [comment]
Thank you!! - but where do I insert these settings? 

... in batocera.conf ?

**Comment by dfilskov** [comment]
Isn't it possible without recompiling?

**Comment by glebm** [comment]
Default font size is informed by the DPI returned by SDL, even if it's wrong that's outside of this app's control.

> global dpi is ignored

The global dpi setting is Batocera-specific. This needs to be fixed on the Batocera side.

**Comment by dfilskov** [comment]
Are you sure this OD Commander uses the DPI from the SDL?

Perhaps OD Commander always uses its own inappropriate default values unless the settings file exists?
(by 'inappropriate' I mean they seem to expect the user to be using an old retro CRT with only 320x240 resolution)

The font size or scaling in OD commander and in Batocera's desktop file manager's terminal look exactly the same.
... but when I change 'global.dpi' in Batocera and reboot only the font size in the terminal changes - not OD commander. Terminal reacts to the change - OD Commander doesn't.

That leads me to think that OD Commander ignores the DPI informed by the SDL.

**Comment by glebm** [comment]
Batocera package actually disables DPI auto-scaling by default here:
https://github.com/batocera-linux/batocera.linux/blob/c7b279b97443b7eea49c6a329d19c486b4e0124a/package/batocera/utils/od-commander/od-commander.mk#L17

I don't remember why that is

**Comment by dfilskov** [comment]
So turning it on in commander.cfg might make OD Commander respond to the global.dpi setting?

**Comment by glebm** [comment]
I don't know how global.dpi works in Batocera but it's worth trying!
