### ISSUE TITLE
DPI arguments and config file path doesn't work

### ISSUE THREAD

**Issue by dfilskov** [od-contrib/commander#21]
No matter what arguments you give it the display DPI is locked.

![IMG_20240513_224624-01](https://github.com/od-contrib/commander/assets/15096058/b379adde-2597-42b1-bad4-466681ab1c8b)

And it hangs if you point --config to a path with a commander.cfg in it

Also it defaults to a write-only path that simply doesn't exist:

/usr/share/od-commander/

... so there's no way for the user to put the arguments in a configuration file.

**Comment by glebm** [comment]
`--config` expects a config file path, not a directory.

https://github.com/od-contrib/commander/blob/079a84c8a8cc25e1899cb11bcfce8e9e2ed9fca9/main.cpp#L80-L84

**Comment by dfilskov** [comment]
It works now - but it seems info on how/where to put settings is missing. I'll try to update the documentation.
