### ISSUE TITLE
Bug report - keyboard doesn't fit

### ISSUE THREAD

**Issue by KoopsF** [od-contrib/commander#3]
-Description of the issue:
When editing a name the keyboard isn't entirely visible.

-Device & OS:
RS-90 & OpenDingux release 2020.01.06

-Commander version:
[commander-rs90.opk](https://github.com/glebm/od-commander/releases/tag/2020-04-04)

**Comment by glebm** [comment]
The keyboard is rendered here:
https://github.com/od-contrib/commander/blob/master/keyboard.cpp

The dimensions of the keyboard itself and each key are currently hardcoded.

To fix this, commander could try to size the keys to fit into the screen dimensions.

**Comment by glebm** [comment]
Released https://github.com/od-contrib/commander/releases/download/2021-03-24/commander-rs90-new-od.opk
